### ISSUE TITLE
Using org.gwtproject.http:gwt-http:1.0.0-RC3 fails finding elemental2 sources

### ISSUE THREAD

**Issue by xamde** [Vertispan/j2clmavenplugin#126]
How to reproduce:

Swap
```
        <dependency>
            <groupId>org.gwtproject.http</groupId>
            <artifactId>gwt-http</artifactId>
            <version>1.0.0-RC3</version>
```
with
```
            <groupId>org.gwtproject.http</groupId>
            <artifactId>gwt-http</artifactId>
            <version>HEAD-SNAPSHOT</version>
```
from github.com/treblereel

and the issue goes away. Or patch `AbstractBuildMojo` to map `Artifact.SCOPE_RUNTIME` to `Dependency.Scope.BOTH` (instead of `RUNTIME`) and the issue goes also away

**Comment by niloc132** [comment]
Thanks for the report and for helping debug this in gitter.

The root cause is that when gradle produces a pom for publishing to maven, it's own api vs implementation distinction is expressed in the maven pom, even though maven doesn't know how to consume it. For traditional Java projects, where the already-compiled bytecode is also present in the repo server this is sufficient, and will help downstream gradle/maven builds to keep their compile classpaths slightly smaller. However, this is harmful for J2CL projects, as unlike jvm bytecode, j2cl output does not have a version imprinted in it, and makes no promises about forward/backward compatibility - an entire application must ensure that it uses this same version of J2CL to build all of its dependencies. Without published transpiled output, the published pom must be assumed to be reliable to not only depend on an artifact, but build against it.

As gwt-http has opted to not produce an accurate pom, the maven side of this project must interpret _all_ `scope=runtime` dependencies as potentially being deliberately incorrect in this way - we can't predict what other projects might also make this same over-optimistic assumption.
