### ISSUE TITLE
<compilationLevel> option not working at j2cl:build

### ISSUE THREAD

**Issue by xiaoxidashen** [Vertispan/j2clmavenplugin#158]
<compilationLevel> option not working on j2cl:build, it works at watch task

**Comment by xiaoxidashen** [comment]
oh,I fix it by change maven path

**Comment by niloc132** [comment]
Can you share your setup? This certainly should work, and in my local testing seems to work.

For example, start with the servlet archetype, and run `mvn package` once, confirm that the output in the client's target dir is ADVANCED. 
Then update the `build` execution like this:
```
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <configuration>
                            <compilationLevel>BUNDLE</compilationLevel>
                        </configuration>
                    </execution>
```
and confirm that the same output file is gigantic, and not optimized at all.

--

The <compilationLevel> on each j2cl:build execution is read by j2cl:watch itself, just like all other configuration settings (except webappDirectory), so that any explicit settings are reflected. If you have a parent pom and run j2cl:watch from there, check that inherited=true is set or not set as expected, so that the setting is inherited. Also consider using a profile to assist in making the configuration flexible, either by setting a maven property, or by defining the plugin configuration there.

**Comment by xiaoxidashen** [comment]
> Can you share your setup? This certainly should work, and in my local testing seems to work.
> 
> For example, start with the servlet archetype, and run `mvn package` once, confirm that the output in the client's target dir is ADVANCED. Then update the `build` execution like this:
> 
> ```
>                     <execution>
>                         <goals>
>                             <goal>build</goal>
>                         </goals>
>                         <configuration>
>                             <compilationLevel>BUNDLE</compilationLevel>
>                         </configuration>
>                     </execution>
> ```
> 
> and confirm that the same output file is gigantic, and not optimized at all.
> 
> --
> 
> The on each j2cl:build execution is read by j2cl:watch itself, just like all other configuration settings (except webappDirectory), so that any explicit settings are reflected. If you have a parent pom and run j2cl:watch from there, check that inherited=true is set or not set as expected, so that the setting is inherited. Also consider using a profile to assist in making the configuration flexible, either by setting a maven property, or by defining the plugin configuration there.

maybe you can try this demo
https://github.com/xiaoxidashen/j2clmavenplugin_demo.git

**Comment by niloc132** [comment]
Sorry for the delay in testing this.

Tested with `mvn install` (or package, verify), and it behaved as expected - the target/compiler-1.0-SNAPSHOT/ directory contains BUNDLEd sources with a single compiler.js file that tries to load them.

However, `mvn j2cl:build` does not produce this output - but this is expected. The <compilationLevel> tag is in the <configuration> for the specific <execution> that was already defined, so it will not apply to just invoking `mvn j2cl:build` directly.

Instead, try either moving that <configuration> block to the top level of your plugin (as below), or passing it as an explicit option from the command line like `mvn j2cl:build -DcompilationLevel=BUNDLE_JAR` - note that this will not work if you also specify compilationLevel in the configuration, since that overrides the default of "read from system property `compilationLevel`.

```
            <plugin>
                <groupId>com.vertispan.j2cl</groupId>
                <artifactId>j2cl-maven-plugin</artifactId>
                <version>0.19</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <compilationLevel>BUNDLE_JAR</compilationLevel>
                </configuration>
            </plugin>
```

Closing for now, please feel free to comment if this isn't clear, or my described fixes don't work for you.
