### ISSUE TITLE
Unable to run j2cl application using 'super-sourced' classes with java 11

### ISSUE THREAD

**Issue by treblereel** [Vertispan/j2clmavenplugin#47]
Errors occurred while running such applications:

```
emul/io/src/main/java/java/io/DataInputStream.java:16: error: package exists in another module: java.base
package java.io;
```

**Comment by niloc132** [comment]
To confirm, you successfully built the original project with java11 also? Meaning the maven-compiler-plugin is passing the right magic flags to javac to say "don't worry about the fact that this already exists in another package"?

We know that j2cl on bazel has no issue with this, since the jre is transpiled via java_common.compile successfully, but I haven't explicitly confirmed that it works on java11 (since i think bazel ships their own jre, i'm just not sure that it is always java8, that would seem to be silly to me).

**Comment by treblereel** [comment]
nope, i am not able to compile it with java 11, only 1.8
you can reproduce it with quake2 for instance, it depends on java.io and java.nio classes, so all you need is check all works great with java 1.8 and failed with java 11

**Comment by niloc132** [comment]
To be clear, just a plain mvn compile on gwt-nio doesn't work either? ignoring j2cl-m-p entirely?

**Comment by treblereel** [comment]
yeap, mvn compile on gwt-nio works, it fails with i am compiling the app with gwt-nio as a dep

**Comment by niloc132** [comment]
Okay, need to take apart either bazel's java_common.compile or maven-compiler-plugin and see what flag they pass to javac to say "shut up and compile this", and add that to our own javac util.
