### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by rendaw** [Vertispan/j2clmavenplugin#66]
I came here interested in trying j2cl out but not interested in converting my whole project to Bazel, so this plugin is much appreciated.  I looked around but I didn't see any instructions for using it.

My understanding is that this automatically translates dependencies, unlike Bazel which appears to require BUILD files for all source?  That sounds like a huge selling point.  So is using this just 1. add plugin to pom, 2. add interop dependency for any interop, 3. that's it?  Does the standard compile step need to be disabled?

Alternatively (or along side it) an example project would be extremely useful.

**Comment by rendaw** [comment]
After reading through the archetype PR I found the tests? Examples? in it/ - maybe a link to those from the readme would be useful.

**Comment by rendaw** [comment]
The plugin doesn't seem to be available in maven central.  I tried adding j2clmavenplugin and Vertispan/j2cl/maven as submodules to my aggregate pom.  After doing `./build.sh` in `j2cl/maven` my maven build gets as far as bootstrap then fails with
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (default) on project bootstrap: Failed to create assembly: Error creating assembly archive jszip: archive cannot be empty -> [Help 1]
```

**Comment by niloc132** [comment]
To run j2cl's maven/build.sh, there is an undeclared dependency that you have a copy of closure-library checked out and up to date "next to" j2cl, since we bundle up the various required files in there.

Please note that we deploy working versions of j2cl to our maven repo at https://repo.vertispan.com/j2cl/ (trailing slash is important) - add this either to your own maven proxy server or to your project both as a repository and as a pluginRepository, and it will provide working j2cl, jsinterop-base (the google-provided implementation in maven central isn't j2cl compatible, and the maven plugin will automatically switch to a working version), and j2cl-maven-plugin builds.

**Comment by rendaw** [comment]
Ah, thanks!  Would you have any objection to this being added to the readme?
